# Generated by Django 3.0.2 on 2020-02-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_down', '0002_auto_20200201_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
