# Generated by Django 3.0.2 on 2020-01-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200114_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default2.png', upload_to='profile_pictures'),
        ),
    ]
