# Generated by Django 3.0 on 2019-12-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizletStudyToolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Quizlet Study Tool Model',
            },
        ),
    ]
