# Generated by Django 3.0 on 2019-12-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet_study_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizletstudytoolmodel',
            name='stopwords',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
