# Generated by Django 3.0 on 2019-12-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet_study_tool', '0002_quizletstudytoolmodel_stopwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizletstudytoolmodel',
            name='num_links',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizletstudytoolmodel',
            name='num_results',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
