# Generated by Django 3.0 on 2019-12-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet_study_tool', '0004_auto_20191220_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizletstudytoolmodel',
            old_name='stopwords',
            new_name='stop_words',
        ),
    ]
