# Generated by Django 3.0 on 2019-12-23 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet_study_tool', '0005_auto_20191221_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizletstudytoolmodel',
            name='num_links',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='quizletstudytoolmodel',
            name='num_results',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
