# Generated by Django 3.0 on 2019-12-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet_study_tool', '0006_auto_20191222_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizletstudytoolmodel',
            name='question',
            field=models.CharField(max_length=2),
        ),
    ]
