# Generated by Django 3.0 on 2019-12-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet_study_tool', '0007_auto_20191223_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizletstudytoolmodel',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
