# Generated by Django 3.0.2 on 2020-01-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet_study_tool', '0008_auto_20191223_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizletstudytoolmodel',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
