# Generated by Django 3.0 on 2019-12-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broken_link_checker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokenLinkCheckerModel',
        ),
    ]
