# Generated by Django 3.0 on 2019-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broken_link_checker', '0003_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenLinkCheckerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
