# Generated by Django 3.0 on 2019-12-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broken_link_checker', '0004_auto_20191218_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokenlinkcheckermodel',
            options={'verbose_name_plural': 'Broken Link Checker Models'},
        ),
    ]
