# Generated by Django 3.0.2 on 2020-01-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broken_link_checker', '0005_auto_20191218_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokenlinkcheckermodel',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
    ]
