# Generated by Django 3.0.2 on 2020-01-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_remove_eventmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestmodel',
            name='created_by',
        ),
    ]
