# Generated by Django 3.0.2 on 2020-01-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_remove_guestmodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmodel',
            name='will_attend',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
