# Generated by Django 3.0.2 on 2020-01-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_auto_20200127_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='token',
            field=models.CharField(blank=True, default='8781d04913514423b0b1ff0ef249fd5d', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guestmodel',
            name='will_attend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
