# Generated by Django 3.0.2 on 2020-01-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_auto_20200127_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestmodel',
            name='token',
        ),
    ]
