# Generated by Django 3.0.2 on 2020-01-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0009_remove_guestmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmodel',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
