# Generated by Django 3.0.2 on 2020-01-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0010_guestmodel_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestmodel',
            name='attending',
        ),
    ]
