# Generated by Django 3.0.2 on 2020-01-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0011_remove_guestmodel_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmodel',
            name='tokenpart2',
            field=models.UUIDField(blank=True, default='bb3f9a40670e42d0b3c90f3e57f2ccb5', null=True),
        ),
    ]
