# Generated by Django 3.0.2 on 2020-01-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0012_guestmodel_tokenpart2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='tokenpart2',
            field=models.UUIDField(blank=True, default='79e3a1429ae74f8b8417dd2b8d338a3f', null=True),
        ),
    ]
