# Generated by Django 3.0.2 on 2020-01-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0013_auto_20200128_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestmodel',
            name='tokenpart2',
        ),
        migrations.AlterField(
            model_name='guestmodel',
            name='token',
            field=models.UUIDField(blank=True, default='011fce2bf22641c0b502f5419db74675', null=True, unique=True),
        ),
    ]
