# Generated by Django 3.0.2 on 2020-01-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0014_auto_20200128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='token',
            field=models.UUIDField(blank=True, default='9e9df6c0aec04b2f9eed45f0bb9554b3', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guestmodel',
            name='will_attend',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
