# Generated by Django 3.0.2 on 2020-01-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0015_auto_20200128_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='token',
            field=models.UUIDField(blank=True, default='64cbfcb2ae3e48a69bac739c028d3089', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guestmodel',
            name='will_attend',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
    ]
