# Generated by Django 3.0.2 on 2020-01-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0016_auto_20200128_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='token',
            field=models.UUIDField(blank=True, default='2b87b20ef0914bedbb2c04e567dada51', null=True, unique=True),
        ),
    ]
