# Generated by Django 3.0.2 on 2020-01-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0017_auto_20200128_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='token',
            field=models.UUIDField(blank=True, default='9c482daa257747949d12f698a9f437ac', null=True, unique=True),
        ),
    ]
