# Generated by Django 3.0.2 on 2020-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0018_auto_20200128_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
