# Generated by Django 3.0.2 on 2020-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0019_auto_20200129_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
