# Generated by Django 3.0.2 on 2020-01-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0021_auto_20200130_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
