# Generated by Django 3.0.2 on 2020-01-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0022_auto_20200130_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
