# Generated by Django 3.0.2 on 2020-01-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0024_remove_eventmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
