# Generated by Django 3.0.2 on 2020-03-04 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0027_auto_20200304_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 4, 13, 2, 59, 774203), null=True),
        ),
    ]
